name: Build & Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# schedule:
#   - cron: '30 5 * * 5'

jobs:

  build:
    runs-on: macos-14
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Select Xcode 15.4
      run: sudo xcode-select -s "/Applications/Xcode_15.4.app"
    - name: Show buildable schemes
      run: xcodebuild -list -project ./DiscoveryProject/TheOneRing.xcodeproj
    - uses: mxcl/xcodebuild@v3
      with:
        platform: iOS
        scheme: 'DarkModeDiscovery'
        action: build
        working-directory: ./DiscoveryProject
        verbosity: xcpretty
        upload-logs: always
        configuration: Release

  unit-tests:
    runs-on: macos-14
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Select Xcode 15.4
      run: sudo xcode-select -s "/Applications/Xcode_15.4.app"
    - name: Show buildable schemes
      run: xcodebuild -list -project ./DiscoveryProject/TheOneRing.xcodeproj
    - uses: mxcl/xcodebuild@v3
      with:
        platform: iOS
        scheme: 'DarkModeDiscovery'
        action: test
        working-directory: ./DiscoveryProject
        verbosity: xcpretty
        upload-logs: always
        configuration: Release
